### ISSUE TITLE
SmileyDB3 Error KeyError: "<class 'float'>" in Insert

### ISSUE THREAD

**Issue by amr2018** [amr2018/SmileyDB3#1]
/AppData/Local/Programs/Python/Python312/Lib/site-packages/SmileyDB3/SmileyDB3.py
Traceback (most recent call last):
  File "c:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\SmileyDB3\SmileyDB3.py", line 344, in <module>
    items.Insert(data = {
  File "c:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\SmileyDB3\SmileyDB3.py", line 78, in Insert
    (_index {self.types['INDEX']}, {self.get_types(data)})
                                    ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\SmileyDB3\SmileyDB3.py", line 60, in get_types
    cols.append(f'{k} {self.types[str(type(data[k]))]}')
                       ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: "<class 'float'>"

**Comment by amr2018** [comment]
Thank you, the problem has been solved 🙂
Uninstall the library

`pip uninstall SmileyDB3`

Install the latest version

`pip install SmileyDB3`
